FROM node:lts-alpine

RUN npm install -g http-server

WORKDIR /app

COPY package*.json ./

RUN npm i

COPY . .

# For dev
# ENTRYPOINT [ "npm", "run", "dev","--", "--host" ]

RUN npm run build

EXPOSE 8080

CMD [ "http-server", "dist" ]